# Generated by Django 3.1.3 on 2020-12-09 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja', models.CharField(max_length=120)),
                ('cidade', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=2)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=120)),
                ('imagem', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cadastrar_Lojas.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.CharField(max_length=10)),
                ('cupom', models.CharField(max_length=20)),
                ('destaque', models.BooleanField()),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cadastrar_Lojas.loja')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cadastrar_Lojas.produto')),
            ],
        ),
    ]
